runtime: nodejs18
service: default

automatic_scaling:
  min_instances: 1
  max_instances: 3
  target_cpu_utilization: 0.65
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

handlers:
  # Expliziter Handler für den Test-Endpunkt
  - url: /api/test
    script: auto
    secure: always

  # Andere API-Endpunkte
  - url: /api/.*
    script: auto
    secure: always

  # Statische Dateien
  - url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|json|svg|woff|woff2|ttf|eot))$
    static_files: frontend/build/\1
    upload: frontend/build/.*\.(js|css|png|jpg|jpeg|gif|ico|json|svg|woff|woff2|ttf|eot)$
    secure: always

  # Alle anderen Anfragen an die React-App weiterleiten
  - url: /.*
    static_files: frontend/build/index.html
    upload: frontend/build/index.html
    secure: always

env_variables:
  NODE_ENV: "production"
  JWT_SECRET: "roboter-verwaltung-secret-key-2025"

instance_class: F2
