runtime: nodejs18
service: default

handlers:
  # Expliziter Handler für den Test-Endpunkt
  - url: /api/test
    script: auto
    secure: always

  # Andere API-Endpunkte
  - url: /api/.*
    script: auto
    secure: always

  # Statische Dateien
  - url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|json|svg|woff|woff2|ttf|eot))$
    static_files: frontend/build/\1
    upload: frontend/build/.*\.(js|css|png|jpg|jpeg|gif|ico|json|svg|woff|woff2|ttf|eot)$
    secure: always

  # Alle anderen Anfragen an die React-App weiterleiten
  - url: /.*
    static_files: frontend/build/index.html
    upload: frontend/build/index.html
    secure: always

env_variables:
  NODE_ENV: "production"
  JWT_SECRET: "your-super-secret-key-change-this-in-production"
  PORT: "8080"

instance_class: F2
